### PR TITLE
Added warnings

### PR DESCRIPTION
**Pull request by edris6**
Added warnings support

### CODE REVIEW

**Comment by edris6** [comment]
Actually im going to make this something like an option in settings. so DONT MERGE YET

**Comment by edris6** [comment]
*wait for next commit

**Comment by edris6** [comment]
Added options

**Comment by virejdasani** [comment]
Thanks a lot for making this but I tried it and I don't see any options to turn warnings on or off.
image
Am I supposed to change the settings from the VSCode command palette?

**Comment by edris6** [comment]
yes on the settings, below extensions
image

**Comment by virejdasani** [comment]
Thanks a lot for doing this!

**Pull request merged**
